FROM node:11.12.0-alpine as node

WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY package*.json ./

RUN npm install

COPY . /usr/src/app/

RUN npm run build

# build nginx

FROM nginx:1.15.9-alpine

COPY --from=node /usr/src/app/build /usr/share/nginx/html

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]